{{- if .Values.leafletReader.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epi-leaflet-reader
  namespace: {{ template "epi.namespace" . }}
  labels:
    {{- include "epi.leafletReaderSelectorLabels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: "CKV_K8S_40=Container is using uid 1000 (predefined user node) by default"
spec:
  replicas: {{ .Values.leafletReader.replicaCount }}
  selector:
    matchLabels:
      {{- include "epi.leafletReaderSelectorLabels" . | nindent 6 }}
{{- with .Values.runner.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "epi.leafletReaderSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "epi.serviceAccountName" . }}
      {{- with .Values.runner.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
      - name: main
        {{- with .Values.runner.securityContext }}
        env:
          - name: READ_ONLY_MODE
            value: "true"
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ include "epi.runner.image" . | quote }}
        imagePullPolicy: {{ .Values.runner.image.pullPolicy | default "Always" }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        {{- with .Values.runner.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.runner.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
          - sh
          - -c
        args:
          - |
            echo "=======> Starting server in read only mode <======="
            npm run server
        volumeMounts:
          - name: epi-external-volume
            mountPath: /ePI-workspace/apihub-root/external-volume
            readOnly: true
          - name: leaflet-reader-secret-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/apihub.json
            subPath: apihub.json
            readOnly: true
          - name: epi-bdns-config-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/bdns.hosts
            subPath: bdns.hosts
            readOnly: true
          - name: epi-secret-volume
            mountPath: /ePI-workspace/env.json
            subPath: env.json
            readOnly: true
          - name: epi-domains-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/{{ required "config.domain must be set" .Values.config.domain }}.json
            subPath: {{ required "config.domain must be set" .Values.config.domain }}.json
            readOnly: true
            {{- if ne .Values.config.domain .Values.config.subDomain }}
          - name: epi-domains-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/{{ required "config.subDomain must be set" .Values.config.subDomain }}.json
            subPath: {{ required "config.subDomain must be set" .Values.config.subDomain }}.json
            readOnly: true
            {{- end}}
          - name: epi-domains-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/{{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            subPath: {{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            readOnly: true
      volumes:
        - name: epi-secret-volume
        {{- if .Values.secretProviderClass.enabled }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "epi.fullname" . }}
        {{- else }}
          secret:
            secretName: {{ include "epi.fullname" . }}
            defaultMode: 0400
        {{- end }}
        - name: leaflet-reader-secret-volume
        {{- if .Values.secretProviderClass.enabled }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: leaflet-reader-secret
        {{- else }}
          secret:
            secretName: {{ include "epi.fullname" . }}
            defaultMode: 0400
        {{- end }}
        - name: epi-bdns-config-volume
          configMap:
            name: {{ include "epi.fullname" . }}-bdns
        - name: epi-domains-volume
          configMap:
            name: {{ include "epi.fullname" . }}-domains
        - name: epi-env-volume
          configMap:
            name: {{ include "epi.fullname" . }}-environment
        - name: epi-external-volume
          persistentVolumeClaim:
            claimName: {{ include "epi.pvc" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}